version: '3.9'

services:

  mongodb-product:
    image: mongo:latest # put the version which you want to use
    container_name: local-mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/product:/data/db
#    command: mongod --auth


  mongo-express-product:
    image: local-mongoexpress
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-product
    depends_on:
      - mongodb-product
    container_name: mongo-express-product
